Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.tago.io', port=443): Max retries exceeded with url: /data/?variable=3grecuc2v&query=last_item (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 27, in get_novus_and_save_in_api
    request = requests.get(parsed_url, headers={"authorization": client.token_service})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.tago.io', port=443): Max retries exceeded with url: /data/?variable=3grecuc2v&query=last_item (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.tago.io', port=443): Max retries exceeded with url: /data/?variable=3grecuc2v&query=last_item (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 27, in get_novus_and_save_in_api
    request = requests.get(parsed_url, headers={"authorization": client.token_service})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.tago.io', port=443): Max retries exceeded with url: /data/?variable=3grecuc2v&query=last_item (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
Failed to complete cronjob at ('* * * * *', 'api.crm.cron.main', '>> /code/api/log/debug7.log 2>&1 ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/code/api/crm/cron.py", line 67, in main
    get_novus_and_save_in_api()
  File "/code/api/crm/cron.py", line 61, in get_novus_and_save_in_api
    id=InteractionDetail.objects.filter(total=duplicate['date_time_medition']).earliest('date_time_medition').id).delete()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1028, in earliest
    return self._earliest(*fields)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1023, in _earliest
    return obj.get()
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
api.crm.models.interaction_detail.InteractionDetail.DoesNotExist: InteractionDetail matching query does not exist.
